config/routes.rb
Rails.application.routes.draw do

  resources :posts
  root 'home#index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  post 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'orders/new', to: 'orders#new'
  post 'orders', to: 'orders#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :order, inverse_of: :foods

  NAMES = %w[ Barany Falafel Tal Tavaszi-salata ].freeze

  PRICES = [890, 1000, 1400, 790].freeze

  INGREDIENTS = [ "darált bárányhús, joghurtos szósz",
                  "falafel, joghurtos szósz",
                  "csirkehús, káposzta, répa, hagyma, saláta, paradicsom vagy csalamádé, joghurtos szósz, csípős szósz, sültkrumpli, pita",
                  "paradicsom, salata, sajt, oliva"].freeze
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :foods, inverse_of: :order, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :foods,
                                allow_destroy: true,
                                reject_if: lambda { |f| f[:quantity].blank? }

  validates :foods, presence: true, :if => lambda { |o| o.current_step == "delivery" }
  validates :customer_name, presence: true, :if => lambda { |o| o.current_step == "delivery" }
  validates :address, presence: true, :if => lambda { |o| o.current_step == "delivery" }
  validates :tele, presence: true, :if => lambda { |o| o.current_step == "delivery" }


  # logic for multiple-step order

  attr_writer :current_step # setter-method for :current_step

  def current_step
    @current_step || steps.first
  end

  def steps
    %w[food delivery].freeze
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    session[:order_params] ||= {}
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]

    Food::NAMES.each_with_index do |name, index|
      @order.foods.build(name: name, price: Food::PRICES[index], ingredients: Food::INGREDIENTS[index])
    end
  end

  def create

    session[:order_params].deep_merge!(params[:order]) if params[:order]
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]
    if params[:back_button]
      @order.previous_step
    elsif @order.last_step?
      @order.save
    else
      @order.next_step
    end
    session[:order_step] = @order.current_step

    binding.irb
    if @order.new_record? && !@order.last_step?
      @order.foods.destroy_all
      Food::NAMES.each_with_index do |name, index|
        @order.foods.build(name: name, price: Food::PRICES[index], ingredients: Food::INGREDIENTS[index])
      end
      render "new"
    else
      session[:order_step] = session[:order_params] = nil
      AppMailer.order_email(User.find_by(email: "samanthatitewebber@gmail.com"), @order).deliver_now
      flash[:notice] = "Order was successfully created."
      redirect_to root_path
    end
  end

  private

    def order_params
      params.require(:order).permit(foods_attributes: [:id, :order_id, :quantity, :name, :ingredients, :price])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Send email to notify user of successful registration
        AppMailer.registration_email(@user).deliver_now

        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:email, :name, :addr, :tele, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/new.html.erb
<%= stylesheet_link_tag "antakya_order_mobile" %>
<%= stylesheet_link_tag "antakya_order_tablet" %>
<%= stylesheet_link_tag "antakya_order_full_screen" %>

<!--Táblázat-->
<div class="responsive">
  <%= form_for @order do |order_form| %>
    <%= render "#{@order.current_step}_step", order_form: order_form %>
    <br>
    <% if @order.last_step? %>
      <%= order_form.submit "Vissza", name:"back_button", class: "ord-btn" %>
      <%= order_form.submit "Rendelés", class: "ord-btn" %>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th Name
      th Title
      th Content
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.name
        td = post.title
        td = post.content
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/shared/_footer.html.erb
<hr class="moving">

<footer>
  <!--Térkép-->
  <div class="googleMap">
    <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1348.7621347454678!2d18.957385301740427!3d47.46021218773051!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xaf733ddcf8761dd5!2zQW50YWt5YSBEw7ZuZXIgVMO2csO2ayBCw7xmw6k!5e0!3m2!1shu!2shu!4v1548010867984"
     width="350" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>

  <div class="social-media">
    <a href="https://www.facebook.com/antakyadonerbudaors/" id="facebook-bottom"><img src="facebook.png" id="facebook-bottom" alt="facebook-icon"></a>
  </div>

  <!--Információk a lap alján is legyenek-->
  <div class="footer-infos">
    <pre id="shop_adress">
      2040 Budaörs Szabadság út 55.
      Tel.:06 70 251 1255
      rendeles.antakya@gmail.com
      (még nem aktív a rendelés)</pre>
      <pre id="open_hours2">
        <ins>Nyitvatartás:</ins>
        Hétfő      10:30-16:00
        Kedd       10:30-16:00
        Szerda     10:30-16:00
        Csütörtök  10:30-16:00
        Péntek     10:30-16:00
        Szombat    Zárva
        Vasárnap   Zárva
      </pre>
    </div>
</footer>



<%= javascript_include_tag "bejelentkezo-ablak" %>

app/views/shared/_header.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="hu"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="hu"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="hu"> <![endif]-->
<!--[if gt IE 8]><!-->
  <title>Antakya Török Büfé - Budaörs</title>
  <%= stylesheet_link_tag "antakyahome_mobile" %>
  <%= stylesheet_link_tag "antakyahome_tablet" %>
  <%= stylesheet_link_tag "antakyahome_full_screen" %>
</head>
  <header>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <!--Információk-->
    <h2>Antakya Török Büfé - Budaörs</h2>
    <pre>
    2040 Budaörs Szabadság út 55.
       Tel.:06 70 251 1255
    rendeles.antakya@gmail.com
    (még nem aktív a rendelés)</pre>
    <pre id="open_hours">
    <ins>Nyitvatartás:</ins>
    Hétfő      10:30-16:00
    Kedd       10:30-16:00
    Szerda     10:30-16:00
    Csütörtök  10:30-16:00
    Péntek     10:30-16:00
    Szombat    Zárva
    Vasárnap   Zárva</pre>
  </header>

app/views/shared/_login_registration.html.erb
<!--Bejelentkező div-->
<div class="login-box">
  <p>Kérjük, hogy az egyéni kedvezményekhez és a gyorsabb rendeléshez jelentkezzen be. Ha nincs fiókja regisztráljon.</p>
  <button type="button" name="login" class="login" onclick="document.getElementById('id01').style.display = 'block'">Bejelentkezés</button>
  <%= button_to "Regisztráció", new_user_url, name: "registration-link", class: "registration-link", method: 'get' %>
</div>
<hr>

<!--Felugró bejelentkező ablak-->
<div class="modal" id="id01">
  <p id="alert"><%= alert %></p>

  <%= form_tag(sessions_path, class: "modal-content animate") do |form| %>
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display = 'none'" class="close" title="Close Modal">&times;</span> <!--X-gomb-->
      <img src="img_avatar.png" alt="avatár-kép" class="avatar"> <!--avatár-kép-->
    </div>
    <div class="container">
      <%= label_tag 'email', 'E-Mail' %>
      <%= text_field_tag 'email', nil, placeholder: 'Írja be az e-mail cimét!', required: true %>

      <%= label_tag 'password', 'Jelszó' %>
      <%= password_field_tag 'password', nil, placeholder: "Írja be a jelszavát!", required: true %>

      <%= submit_tag "Bejelentkezés", class: "bej" %>

      <%= label_tag 'remember', 'Emlékezz rám' %>
      <%= check_box_tag "remember", "yes" %>
    </div>

    <div class="container">
      <button type="button" onclick="document.getElementById('id01').style.display = 'none'" class="cancelbtn">Mégse</button>
      <span class="psw"><a href="###">Elfelejtette jelszavát?</a></span>
    </div>
  <% end %>
</div>

app/views/shared/_menu.html.erb
<nav>

  <!--Menü-->

  <ul>
    <li><%= link_to "Kezdőlap", root_path %></li>
    <li><%= link_to "Étlap/Rendelés(később)", orders_new_path %></li>
    <li><a href="antakya_we.html">Rólunk</a></li>
    <li><a href="antakya_intresting.html">Érdekességek</a></li>
    <li><a href="antakya_akciok.html">Akciók</a></li>
    <li id="facebook"><a href="https://www.facebook.com/antakyadonerbudaors/" id="facebook"><img src="facebook.png" id="facebook" alt="facebook-icon"></a></li>
  </ul>

</nav>
<hr>

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th Password
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = user.password
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="hu" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="hu"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="hu"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="hu"> <![endif]-->
<!--[if gt IE 8]><!-->
    <title>Registráció - Antakya Török Büfé</title>
    <%= stylesheet_link_tag "regisztracio" %>
  </head>
  <body>
    <header>
      <h2>Regisztráció - Antakya Török Büfé</h2>
      <p>Egyéni kevezményekért és az egyszerűbb előrendelés felvételhez illetve kiszállításhoz kérjük töltse ki az alábbi mezőket.</p>
    </header>
    <hr>
    <div class="border">
      <%= form_tag(users_path, class: "reg_form") do |form| %>
        <table>
          <tr>
            <th>
              <%= label_tag 'name', 'Teljes név' %><br>
              <%= text_field_tag 'name', nil, placeholder: 'Írja be a teljes nevét!', required: true %>
            </th>
            <th>
              <%= label_tag 'email', 'Email' %><br>
              <%= text_field_tag 'email', nil, placeholder: 'Írja be az email cimét!', required: true %>
            </th>
          </tr>
          <tr>
            <th>
              <%= label_tag 'addr', 'Cím (nem kötelező)', class: 'right' %><br>
              <%= text_field_tag 'addr', nil, placeholder: 'Azt a címed adja meg ahova az ételeket fogja rendelni!', class: 'right2' %>
            </th>
            <th>
              <%= label_tag 'tele', 'Telefonszám (nem kötelező)', class: 'right' %><br>
              <%= text_field_tag 'tele', nil, placeholder: 'Hogy az előrendelésnél fel tudjuk venni önnel a kapcsolatot kérjük adjon meg egy előrhetőséget!', class: 'right2'%>
            </th>
          </tr>
          <tr>
            <th>
              <%= label_tag 'password', 'Jelszó', class: 'down1' %><br>
              <%= password_field_tag 'password', nil, placeholder: "Válasszon egy erős jelszót!", class: 'down', required: true %>
            <th>
              <%= label_tag 'password', 'Jelszó ismétlése', class: 'down1' %><br>
              <%= password_field_tag 'password_confirmation', nil, placeholder: "Írja be jelszavát még egyszer!", class: 'down', required: true %>
            </th>
          </tr>
        </table>
          <%= submit_tag "Regisztráció", class: "reg" %><br>
      <% end %>
    </div>
    <%= link_to "Mégse", root_path, class: "megse" %><br>
  </body>

</html>

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email
p
  strong Password:
  = @user.password

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path